#!/usr/local/bin/lua

require "ursa"

ursa.rule{"lgl.cpp", {"lgl_make.lua", "descriptor_ogl1.lua"}, "lua lgl_make.lua"}
ursa.rule{"lgl.o", "lgl.cpp", ursa.util.system_template{"g++ -c -o $TARGET $SOURCE -DWIN32"}}

ursa.command{ursa.command.default, "lgl.o"}

ursa.build{...}
